import { boolean, date, integer, jsonb, numeric, pgTable, text, timestamp, unique, uuid, vector } from 'drizzle-orm/pg-core';

const embedding = vector('embedding', { dimensions: 1536 });
export const companies = pgTable('companies', { id: uuid('id').defaultRandom().primaryKey(), name: text('name').notNull(), ticker: text('ticker'), displayOrder: integer('display_order').notNull().default(0), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() });
export const companySources = pgTable('company_sources', { companyId: uuid('company_id').references(() => companies.id, { onDelete: 'cascade' }).notNull(), provider: text('provider').notNull(), config: jsonb('config').$type<Record<string, unknown>>().notNull().default({}) }, table => ({ pk: unique().on(table.companyId, table.provider) }));
export const ingestionRuns = pgTable('ingestion_runs', { id: uuid('id').defaultRandom().primaryKey(), companyId: uuid('company_id').references(() => companies.id), mode: text('mode').notNull(), status: text('status').notNull(), startedAt: timestamp('started_at', { withTimezone: true }), finishedAt: timestamp('finished_at', { withTimezone: true }), error: text('error'), counts: jsonb('counts').$type<Record<string, number>>().notNull().default({}) });
export const sourceDocuments = pgTable('source_documents', { id: uuid('id').defaultRandom().primaryKey(), companyId: uuid('company_id').references(() => companies.id), provider: text('provider').notNull(), providerId: text('provider_id').notNull(), url: text('url'), publishedAt: timestamp('published_at', { withTimezone: true }), rawPayload: jsonb('raw_payload').notNull(), normalizedText: text('normalized_text').notNull(), contentHash: text('content_hash').notNull(), embedding, createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() }, table => ({ providerIdentifier: unique().on(table.provider, table.providerId) }));
export const developments = pgTable('developments', { id: uuid('id').defaultRandom().primaryKey(), companyId: uuid('company_id').references(() => companies.id).notNull(), sourceDocumentId: uuid('source_document_id').references(() => sourceDocuments.id).notNull(), summary: text('summary').notNull(), relevanceScore: numeric('relevance_score').notNull(), status: text('status').notNull().default('new'), embedding, createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() });
export const agentRuns = pgTable('agent_runs', { id: uuid('id').defaultRandom().primaryKey(), companyId: uuid('company_id').references(() => companies.id), mode: text('mode'), status: text('status').notNull(), startedAt: timestamp('started_at', { withTimezone: true }), finishedAt: timestamp('finished_at', { withTimezone: true }), error: text('error'), counts: jsonb('counts').$type<Record<string, number>>().notNull().default({}) });
export const financeAnalyses = pgTable('finance_analyses', { id: uuid('id').defaultRandom().primaryKey(), developmentId: uuid('development_id').references(() => developments.id).notNull(), marketSnapshot: jsonb('market_snapshot').notNull(), impact: text('impact').notNull(), confidence: numeric('confidence').notNull(), rationale: text('rationale').notNull(), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() }, table => ({ development: unique().on(table.developmentId) }));
export const dailyReports = pgTable('daily_reports', { id: uuid('id').defaultRandom().primaryKey(), reportDate: date('report_date').notNull(), summary: text('summary').notNull(), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() });
export const entities = pgTable('entities', { id: uuid('id').defaultRandom().primaryKey(), entityType: text('entity_type').notNull(), label: text('label').notNull(), sourceId: uuid('source_id') });
export const relationships = pgTable('relationships', { id: uuid('id').defaultRandom().primaryKey(), fromEntityId: uuid('from_entity_id').references(() => entities.id).notNull(), toEntityId: uuid('to_entity_id').references(() => entities.id).notNull(), relationshipType: text('relationship_type').notNull(), evidenceDocumentId: uuid('evidence_document_id').references(() => sourceDocuments.id) });
export const documentEntities = pgTable('document_entities', { documentId: uuid('document_id').references(() => sourceDocuments.id).notNull(), entityId: uuid('entity_id').references(() => entities.id).notNull() }, table => ({ link: unique().on(table.documentId, table.entityId) }));
export const calaSnapshots = pgTable('cala_snapshots', { id: uuid('id').defaultRandom().primaryKey(), companyId: uuid('company_id').references(() => companies.id), runId: uuid('run_id').references(() => agentRuns.id), kind: text('kind').notNull(), input: text('input').notNull(), entities: jsonb('entities').$type<unknown[]>().notNull().default([]), results: jsonb('results').$type<unknown[]>().notNull().default([]), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() });
export const healthcareGates = pgTable('healthcare_gates', { id: uuid('id').defaultRandom().primaryKey(), runId: uuid('run_id').references(() => agentRuns.id), companyId: uuid('company_id').references(() => companies.id), isNew: boolean('is_new').notNull(), isRelevant: boolean('is_relevant').notNull(), relevanceScore: numeric('relevance_score').notNull(), rationale: text('rationale').notNull(), developmentSummary: text('development_summary').notNull(), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() });
export const financeImpacts = pgTable('finance_impacts', { id: uuid('id').defaultRandom().primaryKey(), runId: uuid('run_id').references(() => agentRuns.id), companyId: uuid('company_id').references(() => companies.id), developmentSummary: text('development_summary').notNull(), potentialProductOrCatalyst: text('potential_product_or_catalyst').notNull(), expectedImpact: jsonb('expected_impact').notNull(), rationale: text('rationale').notNull(), evidenceIds: jsonb('evidence_ids').$type<string[]>().notNull().default([]), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() });
export const schema = { companies, companySources, ingestionRuns, sourceDocuments, developments, agentRuns, financeAnalyses, dailyReports, entities, relationships, documentEntities, calaSnapshots, healthcareGates, financeImpacts };
