export const schemaStatements = [
  'CREATE EXTENSION IF NOT EXISTS vector',
  `CREATE TABLE IF NOT EXISTS companies (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, ticker text, display_order integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now())`,
  `CREATE TABLE IF NOT EXISTS company_sources (company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE, provider text NOT NULL, config jsonb NOT NULL DEFAULT '{}'::jsonb, PRIMARY KEY(company_id, provider))`,
  `CREATE TABLE IF NOT EXISTS ingestion_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id), mode text NOT NULL CHECK(mode IN ('seed','delta')), status text NOT NULL, started_at timestamptz, finished_at timestamptz, error text, counts jsonb NOT NULL DEFAULT '{}'::jsonb)`,
  `CREATE TABLE IF NOT EXISTS source_documents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id), provider text NOT NULL, provider_id text NOT NULL, url text, published_at timestamptz, raw_payload jsonb NOT NULL, normalized_text text NOT NULL, content_hash text NOT NULL, embedding vector(1536), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(provider, provider_id))`,
  `CREATE TABLE IF NOT EXISTS developments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES companies(id), source_document_id uuid NOT NULL REFERENCES source_documents(id), summary text NOT NULL, relevance_score numeric NOT NULL, status text NOT NULL DEFAULT 'new', embedding vector(1536), created_at timestamptz NOT NULL DEFAULT now())`,
  `CREATE TABLE IF NOT EXISTS agent_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id), mode text, status text NOT NULL, started_at timestamptz, finished_at timestamptz, error text, counts jsonb NOT NULL DEFAULT '{}'::jsonb)`,
  `CREATE TABLE IF NOT EXISTS finance_analyses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), development_id uuid NOT NULL UNIQUE REFERENCES developments(id), market_snapshot jsonb NOT NULL, impact text NOT NULL, confidence numeric NOT NULL, rationale text NOT NULL, created_at timestamptz NOT NULL DEFAULT now())`,
  `CREATE TABLE IF NOT EXISTS daily_reports (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), report_date date NOT NULL, summary text NOT NULL, created_at timestamptz NOT NULL DEFAULT now())`,
  `CREATE TABLE IF NOT EXISTS entities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), entity_type text NOT NULL, label text NOT NULL, source_id uuid)`,
  `CREATE TABLE IF NOT EXISTS relationships (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), from_entity_id uuid NOT NULL REFERENCES entities(id), to_entity_id uuid NOT NULL REFERENCES entities(id), relationship_type text NOT NULL, evidence_document_id uuid REFERENCES source_documents(id))`,
  `CREATE TABLE IF NOT EXISTS document_entities (document_id uuid NOT NULL REFERENCES source_documents(id), entity_id uuid NOT NULL REFERENCES entities(id), PRIMARY KEY(document_id, entity_id))`,
];
