import { useEffect, useState } from 'react';
import { Building2, FileText, Network, Plus, Search, X } from 'lucide-react';
import { listCompanies, type Company } from '../lib/api';

export function Sidebar({ path, onNavigate }: { path: string; onNavigate: (path: string) => void }) {
  const [searchOpen, setSearchOpen] = useState(false);
  const [query, setQuery] = useState('');
  const [companies, setCompanies] = useState<Company[]>([]);
  useEffect(() => { listCompanies().then(setCompanies).catch(() => setCompanies([])); }, []);
  const recent = companies.filter((item) => item.name.toLowerCase().includes(query.toLowerCase())).slice(0, 6);
  const go = (next: string) => onNavigate(next);
  return <aside className="predict-sidebar" aria-label="Workspace navigation"><div className="predict-sidebar-inner"><div className="predict-workspace"><div className="predict-workspace-button" aria-label="Predict workspace"><span className="predict-sidebar-copy">Predict</span></div></div><div className="predict-sidebar-actions"><button className="predict-sidebar-row" onClick={() => go('/')} title="New analysis"><span><Plus size={17} /></span><b className="predict-sidebar-copy">New analysis</b></button><button className={`predict-sidebar-row ${!path.startsWith('/knowledge-graph') && !path.startsWith('/companies/') ? 'is-active' : ''}`} onClick={() => go('/')} title="Companies"><span><Building2 size={17} /></span><b className="predict-sidebar-copy">Companies</b></button><button className={`predict-sidebar-row ${path.startsWith('/knowledge-graph') ? 'is-active' : ''}`} onClick={() => go('/knowledge-graph')} title="Knowledge graph"><span><Network size={17} /></span><b className="predict-sidebar-copy">Knowledge graph</b></button></div><div className="predict-recents"><div className="predict-recents-head"><span className="predict-sidebar-copy">Companies</span><button onClick={() => setSearchOpen((open) => !open)} aria-label="Search companies">{searchOpen ? <X size={15} /> : <Search size={15} />}</button></div>{searchOpen && <div className="predict-recents-search"><Search size={14} /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search companies" /></div>}<div className="predict-recent-list">{recent.map((item) => <button key={item.id} className="predict-recent-row" title={item.name} onClick={() => go(`/companies/${item.id}`)}><FileText size={14} /><span className="predict-sidebar-copy">{item.name}</span></button>)}{query && recent.length === 0 && <span className="predict-empty predict-sidebar-copy">No companies found</span>}</div></div></div></aside>;
}
