export type Company = { id: string; name: string; ticker: string | null; displayOrder: number; createdAt: string };
export type EntityType = 'company' | 'person' | 'institution' | 'paper' | 'patent' | 'clinical_trial' | 'news';
export type Entity = { id: string; type: EntityType; externalId: string | null; label: string; properties: Record<string, unknown> };
export type Person = Entity & { type: 'person' }; export type Institution = Entity & { type: 'institution' };
export type SourceDocument = { id: string; companyId: string | null; provider: string; providerId: string; url: string | null; publishedAt: string | null; rawPayload: unknown; normalizedText: string; contentHash: string; createdAt: string };
export type Relationship = { id: string; type: string; fromEntityId: string; toEntityId: string; sourceDocumentId: string | null; evidenceUrl: string | null; confidence: number };
export type CalaEntity = { id: string; entityType: string; name: string; mentions: number };
export type CalaSnapshot = { id: string; companyId: string; kind: 'healthcare' | 'finance'; input: unknown; entities: CalaEntity[]; results: unknown; createdAt: string };
export type HealthcareGate = { id: string; developmentId: string; isNew: boolean; isRelevant: boolean; relevanceScore: number; rationale: string; developmentSummary: string };
export type Development = { id: string; companyId: string; sourceDocumentId: string; summary: string; relevanceScore: number; status: 'new' | 'analyzed' | 'dismissed'; createdAt: string };
export type ExpectedImpact = { direction: 'up' | 'down' | 'unclear'; magnitude: 'low' | 'medium' | 'high'; horizon: string; confidence: number };
export type FinanceImpact = { id: string; developmentSummary: string; potentialProductOrCatalyst: string; expectedImpact: ExpectedImpact; rationale: string; evidenceIds: string[] };
export type RelationPack = { relationships: Relationship[]; entityIds: string[] };
export type AgentPhase = 'queued' | 'fanout' | 'relations' | 'healthcare_gate' | 'stopped' | 'finance' | 'completed' | 'failed';
export type AgentRun = { id: string; companyId: string | null; mode: 'seed' | 'delta'; status: 'queued' | 'running' | 'completed' | 'failed'; phase: AgentPhase; startedAt: string | null; finishedAt: string | null; error: string | null; counts: Record<string, number> };
export type MomentumReport = { companyId: string; thesis: string; events: Array<{ entityId: string; summary: string; occurredAt: string }>; generatedAt: string };
export type DailyReport = { id: string; reportDate: string; summary: string; createdAt: string };
export type RunInput = { companyId: string; mode: 'seed' | 'delta' };
